version: '3.4'

services:
  apitemplate:
    image: apitemplate
    build:
      context: ./src
      dockerfile: api/Dockerfile
    container_name: "apitemplate"
    ports:
     - $API_PORT:80
    environment: 
     - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - minionetwork
networks:
  minionetwork:
    driver: bridge