version: '3.4'

services:
  mvcui:
    image: mvcui
    build:
      context: ./src
      dockerfile: ui/mvc/Dockerfile
    container_name: "mvcui"
    ports:
     - $MVC_PORT:80
    environment: 
     - ASPNETCORE_ENVIRONMENT=Production
