version: '2.1'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minio1:
  image: minio/minio:$MINIO_VERSION
  container_name: "customminio1"
  volumes:
   - data1:/data
  ports:
   - "9000:9000"
  expose:
    - "9000"
  environment:
   MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
   MINIO_SECRET_KEY: $MINIO_SECRET_KEY
  command: server *
  networks:
    - minionetwork

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:

networks:
  minionetwork:
    driver: bridge