version: '2.1'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minio1:
  image: minio/minio:$MINIO_VERSION
  container_name: $MINIO_PROXY_NAME
  volumes:
   - data1:/data
  ports:
   - "9000:9000"
  environment:
   MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
   MINIO_SECRET_KEY: $MINIO_SECRET_KEY
  command: server data
  networks:
    - minionetwork

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
# volumes:
#   data1: 
volumes:
  data1:
    driver: local
    driver_opts:
      type: none
      device: /Users/temel/Desktop/MiniData
      o: bind
networks:
  minionetwork:
    driver: bridge