version: '2.1'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
 minio1:
  image: minio/minio:$MINIO_VERSION
  volumes:
   - data1:/data
  ports:
   - $MINIO_PORT_1:9000
  environment:
   MINIO_ACCESS_KEY: $M_ACCESS_KEY_FILE
   MINIO_SECRET_KEY: $M_SECRET_KEY_FILE
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio2:
  image: minio/minio:$MINIO_VERSION
  volumes:
   - data2:/data
  ports:
   - $MINIO_PORT_2:9000
  environment:
   MINIO_ACCESS_KEY: $M_ACCESS_KEY_FILE
   MINIO_SECRET_KEY: $M_SECRET_KEY_FILE
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio3:
  image: minio/minio:$MINIO_VERSION
  volumes:
   - data3:/data
  ports:
   - $MINIO_PORT_3:9000
  environment:
   MINIO_ACCESS_KEY: $M_ACCESS_KEY_FILE
   MINIO_SECRET_KEY: $M_SECRET_KEY_FILE
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
 minio4:
  image: minio/minio:$MINIO_VERSION
  volumes:
   - data4:/data
  ports:
   - $MINIO_PORT_4:9000
  environment:
   MINIO_ACCESS_KEY: $M_ACCESS_KEY_FILE
   MINIO_SECRET_KEY: $M_SECRET_KEY_FILE
  command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1:
  data2:
  data3:
  data4:
