version: '2.1'

services:
 minio1:
  image: minio/minio:$MINIO_VERSION
  container_name: "customminio1"
  volumes:
   - data1:/data
  environment:
   MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
   MINIO_SECRET_KEY: $MINIO_SECRET_KEY
  command: server data
  networks:
    - minionetwork
    
 minio2:
  image: minio/minio:$MINIO_VERSION  
  container_name: "customminio2"
  volumes:
   - data1:/data
  environment:
   MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
   MINIO_SECRET_KEY: $MINIO_SECRET_KEY
  command: server data
  networks:
    - minionetwork

 minio3:
  image: minio/minio:$MINIO_VERSION
  container_name: "customminio3"
  volumes:
   - data1:/data
  environment:
   MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
   MINIO_SECRET_KEY: $MINIO_SECRET_KEY
  command: server data
  networks:
    - minionetwork

 minio4:
  image: minio/minio:$MINIO_VERSION
  container_name: "customminio4"
  volumes:
   - data1:/data
  environment:
   MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
   MINIO_SECRET_KEY: $MINIO_SECRET_KEY
  command: server data
  networks:
    - minionetwork
    
 proxy:
  image: minio-proxy
  container_name: $MINIO_PROXY_NAME
  build:
    context: ./proxy
  volumes:
    - data1:/data
  ports:
    - '9000:8080'
  depends_on:
    - minio1
    - minio2
    - minio3
    - minio4
  links:
    - minio1:minio_1
    - minio2:minio_2
    - minio3:minio_3
    - minio4:minio_4
  networks:
    - minionetwork

volumes:
  data1:
    driver: local
    driver_opts:
      type: none
      device: /Users/temel/Desktop/MiniData
      o: bind
networks:
  minionetwork:
    driver: bridge